services:
  web:
    build: .
    ports:
      - "3000:8080"
  bd:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "Mathez"
    volumes:
      - db-data:/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"

volumes:
  db-data:
